config/routes.rb
Rails.application.routes.draw do

  post "join_chatroom" => "chatrooms#join"
  get "join_chatroom/" => "chatrooms#join"


	resources :chatrooms do
		resource :chatroom_users
		resources :messages
	end

  devise_for :users

  root to: "chatrooms#index"

  post "change_chatroom_password" => "chatrooms#change_chatroom_password"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  belongs_to :user
  
  has_many :chatroom_users, dependent: :destroy
	has_many :users, through: :chatroom_users
  has_many :messages, dependent: :destroy

  validates_presence_of :name

end

app/models/chatroom_user.rb
class ChatroomUser < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

	attr_accessor :login

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :chatroom_users
  has_many :chatrooms, through: :chatroom_users
  has_many :messages

	def self.find_for_database_authentication warden_conditions
	  conditions = warden_conditions.dup
	  login = conditions.delete(:login)
	  where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.strip.downcase}]).first
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :configure_permitted_parameters, if: :devise_controller?

  protected

	def configure_permitted_parameters
		 devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password, :password_confirmation])
		 devise_parameter_sanitizer.permit(:sign_in, keys: [:login, :password, :password_confirmation])
		 devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :password, :password_confirmation, :current_password])
	end

end

app/controllers/chatroom_users_controller.rb
class ChatroomUsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_chatroom

  def create
  	@chatroom_user = ChatroomUser.where(chatroom_id: @chatroom.id, user_id: current_user.id).first_or_create
  	redirect_to chatrooms_path
  end

  def destroy
  		@chatroom_user = ChatroomUser.where(chatroom_id: @chatroom.id, user_id: current_user.id).destroy_all
  	redirect_to chatrooms_path
  end

  private

  def set_chatroom
  	@chatroom = Chatroom.find(params[:chatroom_id])
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController

	before_action :authenticate_user!

  def index
  	@chatrooms = ChatroomUser.where(user_id:current_user.id)
		@owned_chatrooms = Chatroom.where(user_id: current_user.id)
		@chatroom = Chatroom.new;
  end

  def join
  	chatroom_id = chatroom_params[:id]
  	password = chatroom_params[:password]
  	@chatroom = Chatroom.where(id: chatroom_id).first
  	if @chatroom.present?
  		if @chatroom.password == password || @chatroom.user_id == current_user.id
    		ChatroomUser.where(chatroom_id: @chatroom.id, user_id: current_user.id).first_or_create
  			flash.notice ="Welcome to #{@chatroom.name}"
  			# byebug
  			# redirect_to chatrooms_path(@chatroom) and return
  			 redirect_to chatroom_path(@chatroom) and return
  		end
  	end
  		flash.alert = "Chatroom or password incorrect"
  		redirect_to chatrooms_path
  end

  def create
  	@chatroom = Chatroom.new(chatroom_params)
  	@chatroom['user_id'] = current_user.id

    if(@chatroom.save )
    	ChatroomUser.where(chatroom_id: @chatroom.id, user_id: current_user.id).first_or_create
      redirect_to chatrooms_path
    else
    	render 'new'
    end
  end

	def show
		@chatroom = Chatroom.where(id: params[:id])
		if @chatroom.present?
			@chatroom=@chatroom.first
			@messages=@chatroom.messages.order(created_at: :desc).limit(100).reverse
			@members = @chatroom.users
			@chatroom_creator_id=@chatroom.user_id
		else
			flash.alert = "Chatroom might have been delete by your friend"
			redirect_to chatrooms_path
		end
	end


	def change_chatroom_password
		@chatroom = Chatroom.find(params[:chatroom_id])
		password = params[:password]
		chatroom_creator_id = @chatroom.user_id
		if chatroom_creator_id == current_user.id
			if @chatroom.update(password: password)
				render json: {password: password}
			else
				password = @chatroom.password
				render json: {password: password}, status: :unprocessable_entity
			end
		else
			render json: {password: password}, status: :unprocessable_entity
		end
	end

	def destroy
		@chatroom = Chatroom.find(params[:id])
		@chatroom.destroy 

		redirect_to chatrooms_path
	end


	def update
		@chatroom = Chatroom.find(params[:id])
		if(@chatroom.update(chatroom_params) )
			redirect_to @chatroom
		else
			render 'edit'
		end
	end

	private

	def chatroom_params
	params.require(:chatroom).permit(:name, :password, :user_id, :id)
	end
  			
 
end

app/controllers/messages_controller.rb
 class MessagesController < ApplicationController
 # skip_before_action :verify_authenticity_token, :only => :create
 #  before_action :authenticate_user!
 #  before_action :set_chatroom

 #  def create
 #  	message = @chatroom.messages.new(message_params)
 #  	message.user = current_user
 #  	message.save
 #    MessageRelayJob.perform_later(message)
 #  redirect_to @chatroom
 #  # respond_to do |format|
 #  #   format.js
 #  # end

 #  end

 #  private

 #  def set_chatroom
 #  	@chatroom = Chatroom.find(params[:chatroom_id])
 #  end

 #  def message_params
 #  	params.require(:message).permit(:body)
 #  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/chatrooms_users_helper.rb
module ChatroomsUsersHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/chatroom_users/create.html.erb
<h1>ChatroomsUsers#create</h1>
<p>Find me in app/views/chatrooms_users/create.html.erb</p>

app/views/chatroom_users/destroy.html.erb
<h1>ChatroomsUsers#destroy</h1>
<p>Find me in app/views/chatrooms_users/destroy.html.erb</p>

app/views/chatrooms/_chatroom_form.html.erb
<%= simple_form_for @chatroom do |f| %>
	<%= f.input :name, label: "Chatroom Name", required: true %>
	<%= f.input :password, as: :string %>
 	<%= f.button :submit,class: "btn btn-primary" %>
<% end %>

app/views/chatrooms/edit.html.erb
<%= render partial: 'chatroom_form' %>

app/views/chatrooms/index.html.erb
<div class="row">
	<div class ="col-sm-5">
		<h5> Create Chatroom </h5>
		<%= render partial: 'chatroom_form' %>
	</div>
	<div class="col-sm-2"></div>
	<div class ="col-sm-5">
		<h5> Join Chatroom </h5>
		<div>
		  <%= simple_form_for @chatroom ,:url => join_chatroom_path, method: :post do |f| %>
		    <%= f.input :id, label: "Chatroom id", autofill: false, required: true %>
		    <%= f.input :password, as: :string,:input_html => { :value => ""} %>
		    <%= f.button :submit,"Join",class: "btn btn-primary" %>
		  <% end %>
		</div>
	</div>
</div>
<br/><br/>
<center><u><h4> All Chatrooms </h4></u></center><br>
<div class="row">
	<div class ="col-sm-5">
		<h5>Created Chatroom </h5>
		<table>
			<% @owned_chatrooms.each do |chatroom| %>
				<tr>
					<td><%= chatroom.name %></td>
					<td><%= link_to "Show",chatroom, class: "btn btn-primary"  %></td>
					<td><%= link_to("Delete", chatroom_path(chatroom),method: :delete, data: {confirm: "Are you sure?"}, :class => "btn btn-danger  ") %> 	</td>
				</tr>
			<%end %>
		</table>
	</div>
	<div class="col-sm-2"></div>
	<div class ="col-sm-5">
		<h5> Joined Chatrooms </h5>
		<table>
			<% @chatrooms.each do |chatroom| %>
				<% if chatroom.chatroom.user_id != current_user.id %>
					<tr>
						<td><%= chatroom.chatroom.name %></td>
						<td><%= link_to "Join",chatroom.chatroom, class: "btn btn-primary" %></td>
						<td><%= link_to "Leave", chatroom_chatroom_users_path(chatroom.chatroom) , method: :delete, data: {confirm: "Are you sure?"} , class: "btn btn-danger"%></td>
					</tr>
				<%end %>
			<%end %>
		</table>
	</div>
</div>

app/views/chatrooms/new.html.erb
<div class="new_chatroom">
	<h5> Create New Chatroom</h5>
</div>

app/views/chatrooms/show.html.erb
<p>
	<h4> <%= @chatroom.name %> </h4>
	id: <%= @chatroom.id%>
</p>
<div class="row">
	<div class="col-sm-9">
		<div data-behavior="messages" data-chatroom-id="<%= @chatroom.id%>">
			<% @messages.each do |message| %>
				<%= render message %>
			<%end %>
		</div>
	 	<%= simple_form_for [@chatroom, Message.new], html: { class: "form-inline" }, remote: true, format: :js do |f| %>
	 		<%= f.input :body, label: false,autofocus: true, class: "form-control" %>
	 		<%= f.button :submit,"Send" %>
	 	<%end%>
	</div>
	<div class="col-sm-3">
		<% if current_user.id == @chatroom_creator_id %>
			password:<div id="password-change-status-<%=@chatroom.id%>"></div>
			<input type="text" value="<%= @chatroom.password %>" id="chatroom-<%=@chatroom.id%>"  class="form-control"><br/>
			<button class="btn btn-primary" data-behavior="change-password-button" data-chatroom-id="<%=@chatroom.id%>">Change</button><br/><br/>
			<textarea value="" id="invite-chatroom-<%=@chatroom.id%>" readonly class="form-control" rows="2" cols="50"></textarea>
			<br/>
			<button class="btn btn-primary" data-behavior="invite-chatroom-button" data-chatroom-id="<%=@chatroom.id%>">Invite Link</button>
			<button class="btn btn-secondary" id="copy-invite-chatroom-<%=@chatroom.id%>" disabled data-behavior="copy-invite-chatroom-button" data-chatroom-id="<%=@chatroom.id%>">copy</button><br/><br/>
		<%end%>
		<h4>Chatroom members</h4>
		<ul>
			<% @members.each do|member| %>
				<li><%= member.username %></li>
			<%end%>
		</ul>
	</div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark"> 
<%= link_to("Guff Chautari", root_path , class: "navbar-brand") %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav w-100">
            <li class="nav-item active dropdown ml-auto">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <%= user_signed_in? ? current_user.username : "Let's Get Started" %>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                  <% if user_signed_in? %>
                    <%= link_to "Edit Profile", edit_user_registration_path, class:"dropdown-item" %> 
                    <%= link_to "Sign Out",destroy_user_session_path, method: :delete, class:"dropdown-item"%>

                  <%else %>
                  <%= link_to "Sign Up",new_user_registration_path, class:"dropdown-item" %>
                  <%= link_to "Login",new_user_session_path, class:"dropdown-item" %>
                  <%end%>
                </div>
            </li>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Guffchautari</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render partial: 'layouts/navbar' %>
    </header>
    <%= bootstrap_flash %>
    <div class="container" style="margin-top: 3rem;">
      <div class="row">
        <div class="col-sm-2">
          <% if user_signed_in? %>
            <h5> Chatrooms </h5>
            <ul>
              <% current_user.chatrooms.each do |chatroom| %>
                <li><%= link_to chatroom.name, chatroom, data: {behavior: "chatroom-link", chatroom_id: chatroom.id } %></li>
              <%end%>
            </ul>
          <%end %>
        </div>
        <div class="col-sm-10">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="message-item"><strong><%= message.user.username %>:</strong> <%= message.body %></div>

app/views/messages/create.js.erb
console.log("hello")